[tool.poetry]
name = "kfpx"
version = "0.0.0"
description = ""
authors = ["Hao Xin <haoxinst@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
